version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: diksha
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - dbvolume:/var/lib/postgresql/data

  backend:
    image: testbackend:v1
    environment:
      DB_USER: diksha
      DB_PASS: test
      DB: test
      DB_HOST: db
    links:
      - db

  frontend:
    image: testfrontend:v1
    ports:
      - 80:5000
    links:
      - backend

volumes:
  dbvolume: